### ISSUE TITLE
efontWrapper Class using Adafruit-GFX-Library for ESP32

### ISSUE THREAD

**Issue by riraosan** [tanakamasayuki/efont#4]
Hello. @tanakamasayuki san. Is this repository active?
Thank you for your contribution to library.

I have created an efont wrapper class for ESP32 to input your BDF font Library into the [Adafruit-GFX-Library](https://github.com/adafruit/Adafruit-GFX-Library) and display it on an LED matrix.
MIT License?
Can I publish it on GitHub? 
Or would you be willing to merge it into your library?
Thank you very much.

**Comment by tanakamasayuki** [comment]
My code is under a CC0 license.
The font has a separate license.
You can fork or PR.

**Comment by tanakamasayuki** [comment]
1.0.5 has been released.

**Comment by riraosan** [comment]
Hello. @tanakamasayuki san

Thank you for your reply.
I will make a pull request when the code is ready.
I would appreciate if you could merge my code.

**Comment by riraosan** [comment]
Hello. @tanakamasayuki san

Thank you for merging my fixes into your library.👍

**Comment by tanakamasayuki** [comment]
Thank you for PR.
It has been adjusted a little for the Arduino IDE.

**Comment by riraosan** [comment]
Hi. @tanakamasayuki san
Why do you have multiple definitions in the header file?
Is there something wrong with the Arduino IDE?
Is it possible that the Arduino IDE cannot compile cpp files?
https://github.com/tanakamasayuki/efont/blob/master/src/efontWrapper.h
https://github.com/tanakamasayuki/efont/blob/master/src/efontWrapper.cpp

If there is a cpp file, PlatformIO will compile to cpp and cause a multiple definition error.
Why don't you delete the cpp file?

**Comment by tanakamasayuki** [comment]
I'm sorry.
I couldn't get it to compile in the Arduino IDE, so I moved it to H.
And I forgot to delete the file.

I've just updated it.

**Comment by riraosan** [comment]
Hello. @tanakamasayuki san
Maybe I'll get a link error in M5StickCPlus.h. Please try to compile and link in Arduino IDE environment.
I want you to use efontWrapper.h and efontWrapper.cpp as a set.👍

**Comment by tanakamasayuki** [comment]
I'm sorry.
I'm busy. Please give me more time.

**Comment by riraosan** [comment]
Hi. @tanakamasayuki

Are you still busy? Since you don't seem to be able to maintain efontWrapper, I'll create an efontwrapper repository and I'll maintain efontwarpper. I'll be happy to use your code. Thank you.
